[project]
name = "llm-dust"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "llm>=0.25",
]

[project.entry-points.llm]
dust = "llm_dust"
