[project]
name = "llm-dust"
version = "0.1.0"
description = "Plugin to add Dust AI support to the LLM CLI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "llm>=0.25",
    "requests>=2.32.3",
]

[project.entry-points.llm]
dust = "llm_dust"
